// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDWPEIMDHz7yL385gatketBY5SCYGgWYs',
    appId: '1:30274804981:web:2ff6e0c90638e85a5679bc',
    messagingSenderId: '30274804981',
    projectId: 'messenger-app-8fad6',
    authDomain: 'messenger-app-8fad6.firebaseapp.com',
    storageBucket: 'messenger-app-8fad6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC06x_X3nmLiPxZjJJw2ljcAzduk6Tlx8g',
    appId: '1:30274804981:android:9dbc261eead129745679bc',
    messagingSenderId: '30274804981',
    projectId: 'messenger-app-8fad6',
    storageBucket: 'messenger-app-8fad6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChzC7kERygTFT6UVhsx8hLwWi6FTv-Fe8',
    appId: '1:30274804981:ios:25b2cce50aac71ef5679bc',
    messagingSenderId: '30274804981',
    projectId: 'messenger-app-8fad6',
    storageBucket: 'messenger-app-8fad6.firebasestorage.app',
    iosBundleId: 'com.example.messengerApp',
  );
}
